mysql:
  dns: root:learn2usemysql@tcp(localhost:3306)/cloud_drive?charset=utf8&parseTime=True&loc=Local
redis:
  addr: "localhost:6379"
  password: ""
  DB: 0
  poolSize: 30
  minIdleConn: 30
qq:
  appID:
  redirectURL: "http://www.pyxgo.cn/callbackQQ"
  appKey:
oss:
  accessKeyID: ""
  accessKeySecret: ""
  endPoint: ""
  BucketName: ""
app:
  JWTKey: "xljjj"